apiVersion: v1
kind: Service
metadata:
  name: erie-chatbot 
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: erie-chatbot
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: erie-chatbot
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: erie-chatbot 
    spec:
      containers:
      - name: erie-chatbot 
        image: kdunetz/kevin-new-chatbot:1.0
        imagePullPolicy: Always 
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 3000
